-- 002_sun_events.sql
-- Seed data for sun events (stub data for development)
-- TODO: Replace with actual Sun Events Scraper (Card 12)

INSERT INTO sun_events (date, location_id, sunrise, sunset, golden_hour_morning_start, golden_hour_morning_end, golden_hour_evening_start, golden_hour_evening_end) VALUES
    -- Dana Point (location_id = 1)
    (CURRENT_DATE, 1, CURRENT_DATE + INTERVAL '6:42', CURRENT_DATE + INTERVAL '18:15', CURRENT_DATE + INTERVAL '6:12', CURRENT_DATE + INTERVAL '6:42', CURRENT_DATE + INTERVAL '17:45', CURRENT_DATE + INTERVAL '18:15'),
    (CURRENT_DATE + INTERVAL '1 day', 1, CURRENT_DATE + INTERVAL '1 day 6:41', CURRENT_DATE + INTERVAL '1 day 18:16', CURRENT_DATE + INTERVAL '1 day 6:11', CURRENT_DATE + INTERVAL '1 day 6:41', CURRENT_DATE + INTERVAL '1 day 17:46', CURRENT_DATE + INTERVAL '1 day 18:16'),
    
    -- La Jolla (location_id = 2)
    (CURRENT_DATE, 2, CURRENT_DATE + INTERVAL '6:38', CURRENT_DATE + INTERVAL '18:12', CURRENT_DATE + INTERVAL '6:08', CURRENT_DATE + INTERVAL '6:38', CURRENT_DATE + INTERVAL '17:42', CURRENT_DATE + INTERVAL '18:12'),
    
    -- Santa Monica (location_id = 3)
    (CURRENT_DATE, 3, CURRENT_DATE + INTERVAL '6:55', CURRENT_DATE + INTERVAL '18:28', CURRENT_DATE + INTERVAL '6:25', CURRENT_DATE + INTERVAL '6:55', CURRENT_DATE + INTERVAL '17:58', CURRENT_DATE + INTERVAL '18:28'),
    
    -- Santa Barbara (location_id = 4)
    (CURRENT_DATE, 4, CURRENT_DATE + INTERVAL '7:05', CURRENT_DATE + INTERVAL '18:38', CURRENT_DATE + INTERVAL '6:35', CURRENT_DATE + INTERVAL '7:05', CURRENT_DATE + INTERVAL '18:08', CURRENT_DATE + INTERVAL '18:38'),
    
    -- Morro Bay (location_id = 5)
    (CURRENT_DATE, 5, CURRENT_DATE + INTERVAL '7:15', CURRENT_DATE + INTERVAL '18:45', CURRENT_DATE + INTERVAL '6:45', CURRENT_DATE + INTERVAL '7:15', CURRENT_DATE + INTERVAL '18:15', CURRENT_DATE + INTERVAL '18:45'),
    
    -- Shaws Cove (location_id = 12)
    (CURRENT_DATE, 12, CURRENT_DATE + INTERVAL '6:42', CURRENT_DATE + INTERVAL '18:15', CURRENT_DATE + INTERVAL '6:12', CURRENT_DATE + INTERVAL '6:42', CURRENT_DATE + INTERVAL '17:45', CURRENT_DATE + INTERVAL '18:15'),
    
    -- Zuma Beach (location_id = 13)
    (CURRENT_DATE, 13, CURRENT_DATE + INTERVAL '6:56', CURRENT_DATE + INTERVAL '18:29', CURRENT_DATE + INTERVAL '6:26', CURRENT_DATE + INTERVAL '6:56', CURRENT_DATE + INTERVAL '17:59', CURRENT_DATE + INTERVAL '18:29')
ON CONFLICT (date, location_id) DO NOTHING;
